name: TiDHy
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.10,<3.12
  - scipy
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - tqdm
  - h5py
  - pytables
  - seaborn
  - ipywidgets
  - jupyter
  - jupyterlab
  - pip
