##### Model dimensions (required) #####
r_dim: ${resolve_default:10,${r_dim}}
r2_dim: ${resolve_default:5,${r2_dim}}
mix_dim: ${resolve_default:15,${mix_dim}}
input_dim: 6
hyper_hid_dim: 32

##### Architecture options #####
loss_type: MSE
nonlin_decoder: false

##### Learning rates (for inference) #####
lr_r: 7.5e-3
lr_r2: 7.5e-3

lr_weights_inf: 0.005
temp_weight: 2.0
spat_weight: 0.5

##### Regularization #####
lmda_r: 0.0
lmda_r2: 0.0
weight_decay: 0.00001
L1_alpha: ${resolve_default:0.0,${L1_alpha}}
L1_inf_w: 0.0
L1_inf_r2: 0.0
L1_inf_r: 0.0
L1_alpha_inf: ${resolve_default:0.0,${L1_alpha_inf}}
L1_alpha_r2: 0.0
grad_alpha_inf: 1.0
clip_grad: 500.0
grad_norm_inf: false


##### Training params #####
max_iter: 1000
tol: 0.01
early_stopping: true  # Enable early stopping in inference (recommended for speed)
normalize_spatial: false
normalize_temporal: false
learning_rate_gamma: 0.5
cos_eta: 5.0

##### Display #####
show_progress: true
show_inf_progress: false