user: eabe

# set the directory where the output files get saved
cwd_dir:  ''
base_dir: /gscratch/portia/${paths.user}/data/TiDHy/${dataset.name}/${version}
save_dir: ${multirun_save_dir:${paths.base_dir},${run_id}}
log_dir:  ${paths.save_dir}/logs/
ckpt_dir: ${paths.save_dir}/ckpt/
fig_dir:  ${paths.save_dir}/figures/
data_dir: /gscratch/portia/${paths.user}/data/TiDHy/datasets/${dataset.name}/