user: eabe

# set the directory where the output files get saved
cwd_dir: ''
base_dir: /data2/users/${paths.user}/TiDHy/${dataset.name}/${version}
save_dir: ${multirun_save_dir:${paths.base_dir},${run_id}}
log_dir:  ${paths.save_dir}/logs/
ckpt_dir: ${paths.save_dir}/ckpt/
fig_dir:  ${paths.save_dir}/figures/
data_dir: /data2/users/${paths.user}/TiDHy/datasets/${dataset.name}/